version: "3.9"

services:
  api:
    build: .
    image: hero-api:latest
    env_file: .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports: ["8000:8000"]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: heroes
      POSTGRES_USER: heroes
      POSTGRES_PASSWORD: heroes
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U heroes -d heroes"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    ports: ["6379:6379"]

  worker:
    build: .
    image: hero-api:latest
    env_file: .env
    depends_on:
      - redis
      - db
    command: celery -A app.celery_app.celery_app worker --loglevel=INFO

  beat:
    build: .
    image: hero-api:latest
    env_file: .env
    depends_on:
      - redis
      - db
    command: celery -A app.celery_app.celery_app beat --loglevel=INFO


